added gigasheet signup mention
crowdsecurity/crowdsec-docs pull request #394
Opened 2023-05-26 08:36 UTC by rr404

2023-10-04 14:37 UTC, buixor approved these changes

2023-11-06 16:57 UTC, LaurenceJJones commented
Please merge main as docusarus v3 has been integrated

2023-11-21 15:51 UTC, LaurenceJJones requested changes
Please merge main

2024-07-23 07:20 UTC, rr404 commented
@LaurenceJJones *an eternity later ...
done

2024-07-24 07:07 UTC, merged