wip: add new appsec options
crowdsecurity/crowdsec-docs pull request #553
Opened 2024-03-29 15:28 UTC by LaurenceJJones

2024-03-29 15:38 UTC, buixor approved these changes

2024-03-29 19:03 UTC, LaurenceJJones commented
Since next is being used for the `1.6.0` release we will wait for `1.6.1` to merge this PR

2024-04-02 10:47 UTC, buixor requested changes

2024-04-02 10:47 UTC, buixor commented on crowdsec-docs/docs/appsec/rules_syntax.md
> +  - `URL_FULL`: The full URL of the request including the query string
URL_FULL -> URI_FULL

2024-04-22 09:39 UTC, buixor approved these changes

2024-04-22 09:40 UTC, merged